### ISSUE TITLE
XSLT Transformation does not view EHF 2.0.

### ISSUE THREAD

**Issue by gunnarvo** [difi/vefa-ehf-xslt#1]
Hi!
I cannot get the XSLT transformation for viewing EHF 2.0 to work correct.
As a test case I use the EHF document "BII05 T10 gyldig faktura.xml" downloaded from vefa-validator-conf-master\STANDARD\EHFInvoice\2.0\guide\Vedlegg_til_veilederen_20\Vedlegg 6 Eksempelfiler\BII05 T10 gyldig faktura.xml
This document valiates OK on Difis online schematron validatator page.

The first two lines in the xml file is:
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="EHF_Invoice_complete.xsl" type="text/xsl" ?>

I have also tried href="EHF_Invoice.xsl" and even pasted the xsl sub files into one main file but to no avail.

What happens when viewing the xml file in Internet Explorer is that all the body text of the xml document is shown "in one line" - as if the xsl file was non-existent.

The xml file and the xsl files all resides on the same directory.
Can someone please shed some light on this issue and pinpoint to me where the problem might reside?
Thanks in advance

Gunnar Vøyenli
Xledger Labs AS

**Comment by klakegg** [comment]
I'm closing this issue because this is related to a stylesheet not provided any more, and the new stylesheet is working fine.
