### ISSUE TITLE
Multiple PaymentTrems not supported

### ISSUE THREAD

**Issue by wernernicolaus** [difi/vefa-ehf-xslt#11]
Multiple elemtents of Invoice/cac:PaymentTrems is not supported. EHF Invoice and Creditnote 2.0.5 specifies the element for 0..unbounded repetitions.

**Comment by SiwMeckelborg** [comment]
I will look into this, and make sure any corrections are done in time for the may revision

**Comment by klakegg** [comment]
This is supported.

XML in file:
```xml
<cac:PaymentTerms>
	<cbc:Note>2 % discount if paid within 2 days</cbc:Note>
</cac:PaymentTerms>
<cac:PaymentTerms>
	<cbc:Note>Penalty percentage 10% from due date</cbc:Note>
</cac:PaymentTerms>
```

Result:
https://test-vefa.difi.no/validator/v/e4891170-58f3-466f-a778-4bce116f71e7/view (to be gone in 14 days.)
