### ISSUE TITLE
XSLT specifies the doctype as http://www.w3.org/TR/html4/loose.dtd but adds xmlns="http://www.w3.org/1999/xhtml"

### ISSUE THREAD

**Issue by SimonsUnikaNamn** [difi/vefa-ehf-xslt#12]
There seems to be an ambiguity if the document should be XHTML or HTML4. 

I wonder if this is correct and it seems to cause problems.

**Comment by SimonsUnikaNamn** [comment]
![screen shot 2016-02-10 at 07 58 18](https://cloud.githubusercontent.com/assets/1564038/12940713/229d2fec-cfcc-11e5-9071-b404c2dac63e.png)

I used both my own implementation and the vefa-validator to render a page from an Invoice. Things work when the filename extension is .html (I'm guessing the doctype is ignored) but since it really is an .xhtml document which have stricter validation this is what is shown when changing the file extension.

Maybe this helps.

**Comment by SiwMeckelborg** [comment]
Thanks. Next release/revision is 23. may, with changes ready for test at latest april 4th. I will review this issue in due time for that revision

**Comment by SimonsUnikaNamn** [comment]
@aberner

**Comment by aberner** [comment]
Vi har leverandører som utvikler mot denne versjonen allerede. De skal være ferdig med utviklingen nå snart og det vil være svært bra om denne feilen kunne rettes asap.

**Comment by SiwMeckelborg** [comment]
Vi har faste releasedatoer, og neste versjon er klar til test senest den 4. April

**Comment by aberner** [comment]
Ja, klar over når releasen deres er. Men en fiks på denne konkrete feilen kan dere legge ut på release-branchen nå.

**Comment by SiwMeckelborg** [comment]
Ah, da misforsto jeg spørsmålet ditt. Skal se om vi kan få prioritert dette, ja.

**Comment by klakegg** [comment]
Fixed, but were not able to reproduce this issue.

**Comment by SimonsUnikaNamn** [comment]
Hi,

I see that the doctype and html tag is now correct. However, now it is not really nice HTML anymore.

Inside the <head> tags I see both <meta> and <link> is not closed as before.

<h2>Leverandør</h2>
               <div xmlns="http://www.w3.org/1999/xhtml" class="UBLBuyerCustomerParty">

There should not be a xmlns tag inside that <div>. I think it comes from commontemplates.xml:s tag 

xmlns="http://www.w3.org/1999/xhtml"

Please take a look.

**Comment by SimonsUnikaNamn** [comment]
Also ```<meta http-equiv="Content-Type" content="text/html; charset=windows-1252"> ```creates issues with norwegian characters, UTF-8 works better.

**Comment by SimonsUnikaNamn** [comment]
This is now a HTML5 document and it is not really valid for this.

You can check it here 

https://validator.w3.org/nu/#textarea

by putting in the file 
[B2C.html.zip](https://github.com/difi/vefa-ehf-xslt/files/142370/B2C.html.zip)

I created this using the new and fixed xslt. The previous xslt created virtually identical result to the DIFI-Validator  (https://github.com/difi/vefa-validator). The xml file used to create this is https://github.com/difi/vefa-validator-conf/blob/master/STANDARD/EHFInvoice/2.0/test/T10-B2C.xml

**Comment by SimonsUnikaNamn** [comment]
I would recommend using XHTML since it is less prone to use the webreaders quirk mode.

**Comment by SimonsUnikaNamn** [comment]
Css does not have a property called border-height used in line 25 in file PEPPOL.css

The lang attribute in line 56 in file Stylesheet_full.xsl is not given correctly, should be lang="{$pLang}" not lang="{pLang}"

**Comment by klakegg** [comment]
I fixed the lang-attribute [yesterday](https://github.com/difi/vefa-ehf-xslt/commit/3282ad0c6a35736daa0662c711dfa0513b54f4b8).

This is an open source project, and you are free to contribute pull requests.

Also I would like to know how it is possible to reproduce the error shown in first post based on the "border-height"-error.

**Comment by SimonsUnikaNamn** [comment]
I'm sorry, didn't see that.

border-height is not valid css, you can check it here

https://jigsaw.w3.org/css-validator/#validate_by_input

Sorry! We found the following errors (1)
URI : TextArea
25	hr	Property border-height doesn't exist : 2px

I don't know what you want to do with it that is why I need your help. 

I will create pull requests of things that I can finx myself from now on :)

**Comment by klakegg** [comment]
* [HTML5 Validation](https://validator.w3.org/nu/?doc=https%3A%2F%2Ftest-vefa.difi.no%2Fvalidator%2Fv%2Fc2d83b71-6f20-4606-9278-58a59ab3b184%2Fview)
* [CSS Validation](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Ftest-vefa.difi.no%2Fehf%2Fxslt%2FEHFInvoice%2F2.0%2FPEPPOL.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en)

I can't find any errors.

Do you **really** need a **perfect** result for test when you know this is **not** the XSLT to be used in the end?

And I still can't reproduce the first error based on an error in the CSS file.

**Comment by SimonsUnikaNamn** [comment]
Maybe there is a misunderstanding, I am not suggesting there are errors now, they have all been fixed which is super :)

I need a close to perfect result since this XSLT will be used now for testing by DIFI and any non valid HTML outputted by the XSLT might make that testing harder.
