### ISSUE TITLE
Feeback on layout of stylsheet

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-ehf-xslt#5]
The following feedback has been provided for the stylesheet of the invoice & credit note:
-------------
PartyID – ukjent begrep for kunden. Dette kan være både kundenummer, leverandørnummer og GLN. Kan det hete forskjellig under leverandør, kunde og betalingsmottaker?

Tilleggsdokumentasjon – Forvirrende informasjon til kunden, og ingen nødvendig informasjon. Må fjernes. 

Betalingstype 31 – Bør heller stå faktura i stedetfor 31. Og kreditnota der det står 30.

Kolonnene kvantitet og enhet står tett, kan disse justeres litt fra hverandre?

Enhet – bruke norske forkortelser

S under Avgift – hva står denne for?

**Comment by jorunnnatvik** [comment]
Hei Siw :-)
Er det mulig å gjøre stylesheetet mindre og mer dynamisk? Vi opplever at det er stort og uhåndterbart, og krever mye skrolling, både opp og ned i dokumentet.

Mvh Jorunn Natvik

**Comment by SiwMeckelborg** [comment]
Ja, vi kan gjøre endringer når det kommer inn forslag sånn som du sender nå. Veldig fint om du kan spesifisere litt mer detaljer om hva du kunne tenke deg å endre. Stylesheet'et slik det foreligger nå, er basert på kravet om at det offentlige må kunne ta stilling til ALL informasjon som sendes i EHF filen. Derfor vises alle elementer som finnes i det instans-dokumentet som er sendt.

**Comment by jorunnnatvik** [comment]
Hei
Vi har jo mulighet for å lage vårt eget stylesheet innenfor vårt ERP-system, men det som er ønskelig tenker jeg, er Difi sitt stylesheet, slik at vi slipper egenutvikling og at alle lovkrav er sikret.
Ellers tenker jeg det er naturlig at Betalingsinformasjon legges i seksjonen for Leverandøren data, og at Kunde og kundeinformasjon ligger i en egen seksjon. Dette vil gjøre at fakturaimaget ikke blir så bredt, og reduserer behovet for skrolling sideveis.
 Avgiftstotaler og Totaler bør ligge under varelinjene.
Jeg synes for øvrig at stylesheetet  rent visuelt er bra (fonter/fet skrift etc), men bredden er et problem, i hvertfall i vår løsning. 
Har ellers stor forståelse for at et standard fakturabilde som skal kunne benyttes av alle er en utfordring å utarbeide.

**Comment by SiwMeckelborg** [comment]
Takk for innspill, kommer tilbake med mer info når vi har vurdert dette.
